3.18. Exception Handling

The syntax of try/catch is as follows:
```php
try {
    ... // Code which might throw an exception
} catch (FirstExceptionClass $exception) {
    ... // Code which handles this exception
} catch (SecondExceptionClass $exception) {
}
```

The TRy {} construct encloses the code that can throw an exception,
try结构里可以抛出异常
which is followed by a series of catch statements, 
后面可以跟着一系列catch结构
each declaring what exception class it handles and under what variable name the exception should be accessible inside the catch block.

When an exception is thrown, the first catch() is reached and an instance of comparison with the declared class is performed.
当有异常产生，会从第一个catch开始检查
If the result is true, the catch block is entered and the exception is made available under the declared variable name.
如果符合，就进入进行操作
If the result is false, the next catch statement is checked. 
Once a catch statement is entered, the following catch statements will not be entered, 
even if the instance of check would result in true. 
一旦有符合的，后面的就不再进行检查
If no catch statements are relevant, 
the language engine checks for additional enclosing try/catch statements in the same function. 
When none exist, it continues searching by unwinding the call stack to the calling functions.

The throw statement
throw 的语法  throw 一个对象
throw <object>;

can only throw an object. You can't throw any basic types such as strings or integers. 
A pre-defined exception class exists called Exception, 
只能throw 一个对象,一个默认的异常类叫做Exception
from which all your exception classes must inherit. 
自定义的异常类都必须要继承这个类
Trying to throw an object which does not inherit from class Exception will result in a final runtime error.
如果throw的对象没有继承这个异常类会报final错误

The following code snippet shows the interface of this built-in exception class 
(the square brackets in the constructor declaration are used to represent optional parameters, which are not valid PHP syntax):
下面是自定义异常类的示范
```php
class Exception {
    function __construct([$message [,$code]]);

    final public getMessage();
    final public getCode();
    final public getFile();
    final public getLine();
    final public getTrace();
    final public getTraceAsString();

    protected $message;
    protected $code;
    protected $file;
    protected $line;
}



The following is a full-blown example of exception handling:

class NullHandleException extends Exception {
    function __construct($message)
    {
        parent::__construct($message);
    }
}

function printObject($obj)
{
    if ($obj == NULL) {
         throw new NullHandleException("printObject received NULL object");
    }
    print $obj . "\n";
}

class MyName {
    function __construct($name)
    {
        $this->name = $name;
    }

    function __toString()
    {
        return $this->name;
    }

    private $name;
}

try {
    printObject(new MyName("Bill"));
    printObject(NULL);
    printObject(new MyName("Jane"));
} catch (NullHandleException $exception) {
    print $exception->getMessage();
    print " in file " . $exception->getFile();
    print " on line " . $exception->getLine() . "\n";
} catch (Exception $exception) {
    // This won't be reached
}
```

Running this script prints
Bill
printObject received NULL object in file C:\projects\php5\tests\test.php on line
12当有异常发生时，后面的代码就会被跳过

by default, new calls the parent constructor. 
默认实例化一个新类会调用父类的constructor
However, it is good practice to add a constructor and call the parent constructor explicitly 
so that you don't forget to do so if you suddenly decide to add a constructor of your own.
一般在子类的初始化函数中加parent::__construct($message);这样在你需要给子类定义初始化函数就不会出错


Remember that exceptions are exceptions. You should only use them to handle problems, which brings us to the next rule….
异常就是异常，不要让它进入另一个逻辑判读
Never use exceptions for flow control. 
This makes the code hard to follow (similar to the goto statement found in some languages) and is slow.
不要在控制流语句中使用异常，会导致代码难以追踪和变慢

The exception should only contain the error information and shouldn't contain parameters 
(or additional information) that affect flow control and logic inside the catch handler.
异常中只能包含异常异性，不要在里面做逻辑处理







